version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A web worker -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A web beat -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
