# Generated by Django 3.2.11 on 2022-01-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField()),
                ('category', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('data', models.JSONField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
